from tkinter import*
root = Tk()

frame_usuario_1=Frame(root, width=400, height=200, bg="#ffba82")
frame_usuario_1.grid(row=0, column=0)
frame_usuario_2= Frame(root, width=400, height=200, bg="#ff8f33")
frame_usuario_2.grid(row=1, column=0)
def enviar_1():
    mensaje_emisor= mensaje_1.get()
    label_emisor.config(text=mensaje_emisor)
    label_emisor.grid(row=0, column=0)
    mensaje_1.delete(0,END)
def enviar_2():
    mensaje_receptor = mensaje_2.get()
    label_receptor.config(text=mensaje_receptor)
    label_receptor.grid(row=0, column=0)
    mensaje_2.delete(0, END)
mensaje_1 = Entry(frame_usuario_1)
mensaje_1.grid(row=0, column=1)
usuario_1= Label(frame_usuario_1, text="Usuario 1")
usuario_1.grid(row=0, column=2)
boton_enviar_1 = Button(frame_usuario_1, text="Enviar", command=enviar_1)
boton_enviar_1.grid(row=0, column=0)
mensaje_2 = Entry(frame_usuario_2)
mensaje_2.grid(row=0, column=1)
usuario_2= Label(frame_usuario_2, text="Usuario 2")
usuario_2.grid(row=0, column=0)
boton_enviar_2= Button(frame_usuario_2, text="Enviar", command=enviar_2)
boton_enviar_2.grid(row=0, column=2)
frame_emisor=Frame(root, width=400, height=200, bg="#ffba82")
frame_emisor.grid(row=2, column=0)
frame_receptor= Frame(root, width=400, height=200, bg="#ff8f33")
frame_receptor.grid(row=3, column=0)
label_emisor= Label(frame_emisor, text="")
label_receptor= Label(frame_receptor, text="")
root.mainloop()